import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Tan',
      email: 'a@i.c',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'AdminS',
        description: 'AdminS',
        rating: 5,
        numReviews: 10,
      },
    },
    {
      name: 'J',
      email: 'u@i.c',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'H',
      email: 'user1@e.c',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 's',
      email: 's@i.c',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'S',
        description: 's',
        rating: 4,
        numReviews: 6,
      },
    },
    {
      name: 's2',
      email: 'seller2@e.c',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'S2',
        description: 's2',
        rating: 3.5,
        numReviews: 10,
      },
    },
  ],
  products: [
    {
      name: 'Dell 7240',
      slug: 'Dell-7240',
      category: 'Laptop',
      image: '/images/Dell_7240_6100000.png',
      price: '6100000',
      stock: '10',
      brand: 'Dell',
      rating: 4.5,
      numReviews: 10,
      description: 'Dell',
    },
    {
      name: 'Dell 7270',
      slug: 'Dell-7270',
      category: 'Laptop',
      image: '/images/Dell_7270_7800000.png',
      price: '7800000',
      stock: '10',
      brand: 'Dell',
      rating: 3.5,
      numReviews: 10,
      description: 'Dell',
    },
    {
      name: 'LG G6',
      slug: 'LG-G6',
      category: 'Smartphone',
      image: '/images/LG_G6_1549000.png',
      price: '1549000',
      stock: '10',
      brand: 'LG',
      rating: 2.0,
      numReviews: 10,
      description: 'LG',
    },
    {
      name: 'LG G8',
      slug: 'LG-G8',
      category: 'Smartphone',
      image: '/images/LG_G8_2999000.png',
      price: '2999000',
      stock: '10',
      brand: 'LG',
      rating: 4.5,
      numReviews: 10,
      description: 'LG',
    },
    {
      name: 'OPPO F1S',
      slug: 'OPPO-F1S',
      category: 'Smartphone',
      image: '/images/OPPO_F1S_1498000.png',
      price: '1498000',
      stock: '10',
      brand: 'OPPO',
      rating: 4.5,
      numReviews: 10,
      description: 'OPPO',
    },
    {
      name: 'OPPO-F9',
      slug: 'OPPO-F9',
      category: 'Smartphone',
      image: '/images/OPPO_F9_2499000.png',
      price: '2499000',
      stock: '10',
      brand: 'OPPO',
      rating: 4.5,
      numReviews: 10,
      description: 'OPPO',
    },
    {
      name: 'Samsung A50s',
      slug: 'Samsung-A50s',
      category: 'Smartphone',
      image: '/images/Samsung_A50s_1218822.png',
      price: '1218822',
      stock: '10',
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 10,
      description: 'Samsung',
    },
    {
      name: 'Samsung S9',
      slug: 'Samsung-S9',
      category: 'Smartphone',
      image: '/images/Samsung_S9_3199000.png',
      price: '3199000',
      stock: '10',
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 10,
      description: 'Samsung',
    },
  ],
};
export default data;
